resolver: ghc-9.2.1
allow-newer: true
extra-deps:
- adjunctions-4.4
- ansi-terminal-0.11.1
- ansi-wl-pprint-0.6.9
- assoc-1.0.2
- base-orphans-0.8.6
- bifunctors-5.5.11
- call-stack-0.4.0
- case-insensitive-1.2.1.0
- clock-0.8.2
- colour-2.3.6
- comonad-5.0.8
- contravariant-1.5.5
- data-default-class-0.1.2.0
- data-fix-0.3.2
- distributive-0.6.2.1
- dlist-1.0
- either-5.0.1.1
- foldl-1.4.12
- free-5.1.7
- groups-0.5.3
- hashable-1.4.0.2
- hashable-time-0.3
- indexed-traversable-0.1.2
- integer-logarithms-1.0.3.1
- invariant-0.5.5
- kan-extensions-5.2.3
- keys-3.12.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- OneTuple-0.3.1
- optparse-applicative-0.16.1.0
- pointed-5.0.3
- primitive-0.7.3.0
- profunctors-5.6.2
- QuickCheck-2.14.2
- quickcheck-instances-0.3.27
- random-1.2.1
- rebase-1.14
- rerebase-1.14
- scientific-0.3.7.0
- selective-0.5
- semigroupoids-5.3.7
- semigroups-0.20
- splitmix-0.1.0.4
- StateVar-1.2.2
- strict-0.4.0.1
- tagged-0.8.6.1
- tasty-1.4.2.1
- tasty-hunit-0.10.0.3
- tasty-quickcheck-0.10.2
- text-2.0
- text-short-0.1.5
- th-abstraction-0.4.3.0
- these-1.1.1.1
- time-compat-1.9.6.1
- transformers-base-0.4.6
- transformers-compat-0.7.1
- unbounded-delays-0.1.1.1
- unordered-containers-0.2.16.0
- uuid-types-1.0.5
- vector-0.12.3.1
- vector-instances-3.4
- void-0.7.3
- wcwidth-0.0.2
